---
- hosts: localhost
  connection: local
  become: true
  vars:
    elasticsearch_dl_file: 'elasticsearch-{{ elasticsearch_ver }}.tar.gz'
    elasticsearch_url: 'https://artifacts.elastic.co/downloads/elasticsearch'
    gosu_ver: '1.9'
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: Installing ca-certificates
      apk:
        name: "ca-certificates"
        state: "present"

    - name: Installing gosu
      get_url:
        url: "https://github.com/tianon/gosu/releases/download/{{ gosu_ver }}/gosu-amd64"
        dest: "/usr/local/bin/gosu"
        mode: 0755

    - name: Installing Elasticsearch Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'bash'
        - 'tar'

    - name: Ensuring /usr/local/lib Exists
      file:
        path: "/usr/local/lib"
        state: "directory"

    - name: Checking For Elasticsearch User
      shell: "cut -d: -f1 /etc/passwd"
      register: "users_list"

    - name: Creating Elasticsearch User
      command: "adduser -DH -s /sbin/nologin elasticsearch"
      when: users_list.stdout.find('elasticsearch') != 1

    - name: Downloading Elasticsearch
      get_url:
        url: "{{ elasticsearch_url }}/{{ elasticsearch_dl_file }}"
        dest: "/usr/share/{{ elasticsearch_dl_file }}"

    - name: Extracting Elasticsearch
      unarchive:
        src: "/usr/share/{{ elasticsearch_dl_file }}"
        dest: "/usr/share"
        owner: "elasticsearch"
        group: "elasticsearch"
        copy: no

    - name: Creating Elasticsearch Symlink
      file:
        src: "/usr/share/elasticsearch-{{ elasticsearch_ver }}"
        dest: "/usr/share/elasticsearch"
        state: "link"

    - name: Ensuring Elasticsearch Folders Exist
      file:
        path: "/usr/share/elasticsearch/{{ item }}"
        state: "directory"
        owner: "elasticsearch"
        group: "elasticsearch"
      with_items:
        - 'config'
        - 'config/scripts'
        - 'data'
        - 'logs'
        - 'plugins'

    - name: Cleaning Up
      file:
        path: "{{ item }}"
        state: "absent"
      with_items:
        - '/usr/share/{{ elasticsearch_dl_file }}'
