version: '2'
services:
  elasticsearch:
    image: mrlesmithjr/elasticsearch:latest
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

volumes:
  elasticsearch:
